global:
  resolve_timeout: 5m
alerting:
  alertmanagers:
      static_configs:
        - targets: ['localhost:9093']
route:
 group_by: ['job']
 group_wait: 10s
 group_interval: 5m
 receiver: 'webhook'

receivers:
- name: 'webhook'
  webhook_configs:
  - url: 'http://alertmanager-webhook:5001/alert'
