groups:
- name: example
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

  - alert: HighCpuUsage
    expr: node_cpu_usage > 90
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage on {{ $labels.instance }}"
      description: "CPU usage on {{ $labels.instance }} is above 90% for more than 10 minutes."

  - alert: DiskAlmostFull
    expr: node_filesystem_free < 1e+08
    for: 15m
    labels:
      severity: critical
    annotations:
      summary: "Disk space low on {{ $labels.device }}"
      description: "Free disk space on {{ $labels.device }} is less than 100MB for more than 15 minutes."

