global:
  scrape_interval: 10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/alertmanager_rules.yml  

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
        

  - job_name: 'alertmanager'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9093']



  - job_name: 'nginx'                                                                                                                                           scrape_interval: 5s
    static_configs:                                                                                                                                               - targets:
        - https://lhind-demo.l1anu.online/                                                                                                                  ~                                                                                                                                                           ~                                                    
